name: "base"
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bc
  - bcftools
  - bzip2
  - freebayes
  - gatk4
  - octopus
  - parallel
  - pysam
  - rtg-tools
  - samtools
  - sed
  - vcflib
  - yaml
  - kmc
  - smudgeplot
  - genomescope2
  - hifiasm
  - minimap2
  - purge_dups
prefix: "/opt/conda"

