name: "base"
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - argcomplete=3.1.1
  - attrs=23.1.0=pyh71513ae_1
  - bc=1.07.1
  - bcftools=1.15
  - bioconductor-annotationdbi=1.56.2=r41hdfd78af_0
  - bioconductor-biobase=2.54.0=r41hc0cfd56_2
  - bioconductor-biocfilecache=2.2.0=r41hdfd78af_0
  - bioconductor-biocgenerics=0.40.0=r41hdfd78af_0
  - bioconductor-biocio=1.4.0=r41hdfd78af_0
  - bioconductor-biocparallel=1.28.3=r41hc247a5b_1
  - bioconductor-biomart=2.50.0=r41hdfd78af_0
  - bioconductor-biostrings=2.62.0=r41hc0cfd56_2
  - bioconductor-bsgenome=1.62.0=r41hdfd78af_0
  - bioconductor-data-packages=20230420=hdfd78af_0
  - bioconductor-delayedarray=0.20.0=r41hc0cfd56_2
  - bioconductor-genomeinfodb=1.30.1=r41hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
  - bioconductor-genomicalignments=1.30.0=r41hc0cfd56_2
  - bioconductor-genomicfeatures=1.46.1=r41hdfd78af_0
  - bioconductor-genomicranges=1.46.1=r41hc0cfd56_1
  - bioconductor-iranges=2.28.0=r41hc0cfd56_2
  - bioconductor-keggrest=1.34.0=r41hdfd78af_0
  - bioconductor-matrixgenerics=1.6.0=r41hdfd78af_0
  - bioconductor-rhtslib=1.26.0=r41hc0cfd56_2
  - bioconductor-rsamtools=2.10.0=r41hc247a5b_2
  - bioconductor-rtracklayer=1.54.0=r41h171f361_4
  - bioconductor-s4vectors=0.32.4=r41hc0cfd56_0
  - bioconductor-summarizedexperiment=1.24.0=r41hdfd78af_0
  - bioconductor-variantannotation=1.40.0=r41hc0cfd56_2
  - bioconductor-xvector=0.34.0=r41hc0cfd56_2
  - bioconductor-zlibbioc=1.40.0=r41hc0cfd56_2
  - boost-cpp=1.74.0=h6cacc03_7
  - boto=2.49.0=py_0
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - conda-pack=0.7.0=pyh6c4a22f_0
  - curl=7.86.0=h7bff187_1
  - distro=1.8.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freebayes=1.3.6=h346b5cb_1
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - gatk4=4.3.0.0=py36hdfd78af_0
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_13
  - gcs-oauth2-boto-plugin=3.0=pyhd8ed1ab_1
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=10.4.0=h7d168d2_19
  - gfortran_linux-64=10.4.0=h69d5af5_13
  - giflib=5.2.1=h0b41bf4_3
  - gmp=6.2.1=h58526e2_0
  - google-apitools=0.5.32=pyhd8ed1ab_0
  - google-auth=2.21.0=pyh1a96a4e_0
  - google-reauth=0.1.1=pyhd3deb0d_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gsutil=5.25=pyhd8ed1ab_0
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_13
  - harfbuzz=4.2.0=h40b6f09_0
  - htslib=1.14=h9753748_2
  - httplib2=0.20.4=pyhd8ed1ab_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jq=1.5=0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=17_linux64_openblas
  - libcblas=3.9.0=17_linux64_openblas
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.86.0=h7bff187_1
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.74.1=h7a41b64_0
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.4.0=h0e0dad5_3
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=haae042b_4
  - libzlib=1.2.13=hd590300_5
  - make=4.3=hd18ef5c_1
  - monotonic=1.5=py_0
  - ncurses=6.4=hcb278e6_0
  - oauth2client=4.1.3=py_0
  - octopus=0.7.4=ha3c1580_2
  - openjdk=11.0.1=h516909a_1016
  - pango=1.50.7=hbd2fdc8_0
  - parallel=20170422=pl5.22.0_0
  - pcre2=10.37=hc3806b6_1
  - perl=5.22.0.1=0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pysam
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3
  - r-askpass=1.1=r41h06615bd_3
  - r-assertthat=0.2.1=r41hc72bb7e_3
  - r-base=4.1.3=hd930d0e_0
  - r-bh=1.81.0_1=r41hc72bb7e_0
  - r-bit=4.0.5=r41h06615bd_0
  - r-bit64=4.0.5=r41h06615bd_1
  - r-bitops=1.0_7=r41h06615bd_1
  - r-blob=1.2.4=r41hc72bb7e_0
  - r-cachem=1.0.8=r41h57805ef_0
  - r-cli=3.6.1=r41h38f115c_0
  - r-codetools=0.2_19=r41hc72bb7e_0
  - r-cpp11=0.4.3=r41hc72bb7e_0
  - r-crayon=1.5.2=r41hc72bb7e_1
  - r-curl=4.3.3=r41h06615bd_1
  - r-data.table=1.14.8=r41h133d619_0
  - r-dbi=1.1.3=r41hc72bb7e_1
  - r-dbplyr=2.3.2=r41hc72bb7e_0
  - r-digest=0.6.31=r41h38f115c_0
  - r-dplyr=1.1.2=r41ha503ecb_0
  - r-ellipsis=0.3.2=r41h06615bd_1
  - r-fansi=1.0.4=r41h133d619_0
  - r-fastmap=1.1.1=r41h38f115c_0
  - r-filelock=1.0.2=r41h133d619_1003
  - r-formatr=1.14=r41hc72bb7e_0
  - r-futile.logger=1.4.3=r41hc72bb7e_1004
  - r-futile.options=1.0.1=r41hc72bb7e_1003
  - r-generics=0.1.3=r41hc72bb7e_1
  - r-getopt=1.20.3=r41ha770c72_3
  - r-glue=1.6.2=r41h06615bd_1
  - r-gridextra=2.3=r41hc72bb7e_1004
  - r-gtable=0.3.3=r41hc72bb7e_0
  - r-hms=1.1.3=r41hc72bb7e_0
  - r-httr=1.4.6=r41hc72bb7e_0
  - r-jsonlite=1.8.5=r41h57805ef_0
  - r-lambda.r=1.2.4=r41hc72bb7e_2
  - r-lattice=0.21_8=r41h133d619_0
  - r-lifecycle=1.0.3=r41hc72bb7e_1
  - r-magrittr=2.0.3=r41h06615bd_1
  - r-matrix=1.5_4.1=r41h316c678_0
  - r-matrixstats=1.0.0=r41h57805ef_0
  - r-memoise=2.0.1=r41hc72bb7e_1
  - r-mime=0.12=r41h06615bd_1
  - r-openssl=2.0.5=r41hb1dc35e_0
  - r-optparse=1.7.3=r41hc72bb7e_1
  - r-pillar=1.9.0=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_2
  - r-plogr=0.2.0=r41hc72bb7e_1004
  - r-png=0.1_8=r41h10cf519_0
  - r-prettyunits=1.1.1=r41hc72bb7e_2
  - r-progress=1.2.2=r41hc72bb7e_3
  - r-purrr=1.0.1=r41h133d619_0
  - r-r6=2.5.1=r41hc72bb7e_1
  - r-rappdirs=0.3.3=r41h06615bd_1
  - r-rcpp=1.0.10=r41h38f115c_0
  - r-rcurl=1.98_1.12=r41h133d619_0
  - r-restfulr=0.0.15=r41h73dbb54_0
  - r-rjson=0.2.21=r41h7525677_2
  - r-rlang=1.1.1=r41ha503ecb_0
  - r-rsqlite=2.3.1=r41h38f115c_0
  - r-snow=0.4_4=r41hc72bb7e_1
  - r-stringi=1.7.6=r41h337692f_1
  - r-stringr=1.5.0=r41h785f33e_0
  - r-sys=3.4.2=r41h57805ef_0
  - r-tibble=3.2.1=r41h133d619_1
  - r-tidyr=1.3.0=r41h38f115c_0
  - r-tidyselect=1.2.0=r41hc72bb7e_0
  - r-utf8=1.2.3=r41h133d619_0
  - r-vctrs=0.6.2=r41ha503ecb_0
  - r-withr=2.5.0=r41hc72bb7e_1
  - r-xml=3.99_0.11=r41h2b86b34_2
  - r-xml2=1.3.3=r41h044e5c7_2
  - r-yaml=2.3.7=r41h133d619_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - retry_decorator=1.1.1=py_0
  - rsa=4.7.2=pyh44b312d_0
  - rtg-tools=3.12.1=hdfd78af_0
  - samtools=1.15=h3843a85_0
  - sed=4.8=he412f7d_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sysroot_linux-64=2.12=he073ed8_15
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vcflib=1.0.3=hecb563c_1
  - yaml=0.2.5=h7f98852_2
prefix: "/opt/conda"

