name: "base"
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bc
  - bcftools
  - bioconductor-biostrings
  - bioconductor-genomicranges
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-variantannotation
  - bzip2
  - freebayes
  - gatk4
  - octopus
  - parallel
  - pysam
  - r-base
  - r-data.table
  - r-tidyverse
  - r-optparse
  - r-gridextra
  - r-purrr
  - r-stringr
  - rtg-tools
  - samtools
  - sed
  - vcflib
  - yaml
prefix: "/opt/conda"

